apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
  namespace: ai-production
data:
  SYSTEM_PROMPT: "You are BankBot, a professional banking support assistant."
  RISK_API_URL:  "http://risk-service:8001"
  OLLAMA_URL:    "http://ollama-service:11434"
  OLLAMA_MODEL:  "llama3.2"
  BOT_NAME:      "BankBot"
  APP_ENV:       "production"
  LOG_DIR:       "/shared/logs"
  MODEL_DIR:     "/model"
